name: mapmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  dio: ^5.5.0+1
  intl: ^0.18.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mallbanner.jpg
    - assets/images/bookbanner.jpg
    - assets/images/bookDialogBanner.jpeg
    - assets/images/map.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 700